---
- name: install-iis
  win_feature:
    name: "Web-Server"
    state: present
    restart: no
    include_sub_features: yes
    include_management_tools: yes
- name: website-template
  template:
    src: index.html.j2
    dest: "C:\\inetpub\\wwwroot\\index.html"